import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Check, Copy, ExternalLink, ChevronRight, Info } from "lucide-react";

type ResourcesPageProps = {
  onNavigateToDocs?: () => void;
  onStartEarning?: () => void;
};

type TabId = "abstract" | "tokenomics" | "cryptography";

// Fixed layout for the hero mesh diagram — each point stands in for a real
// node region, so the diagram reads as "the network," not decoration.
const meshNodes = [
  { id: "n1", x: 60, y: 70, label: "H100 · London" },
  { id: "n2", x: 210, y: 40, label: "A100 · Singapore" },
  { id: "n3", x: 320, y: 110, label: "RTX4090 · Austin" },
  { id: "n4", x: 140, y: 160, label: undefined },
  { id: "n5", x: 260, y: 200, label: undefined },
  { id: "n6", x: 40, y: 210, label: undefined },
];

const meshLinks: [string, string][] = [
  ["n1", "n2"],
  ["n2", "n3"],
  ["n1", "n4"],
  ["n4", "n2"],
  ["n4", "n6"],
  ["n4", "n5"],
  ["n5", "n3"],
];

export default function ResourcesPage({
  onNavigateToDocs,
  onStartEarning,
}: ResourcesPageProps = {}) {
  // Whitepaper active section
  const [activeResTab, setActiveResTab] = useState<TabId>("abstract");

  // Terminal commands copy state
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  // Live network stats simulation
  const [onChainNodes, setOnChainNodes] = useState<number>(14208);
  const [microSolTps, setMicroSolTps] = useState<number>(452);
  const [totalSolBurnt, setTotalSolBurnt] = useState<number>(121.84);

  useEffect(() => {
    const interval = setInterval(() => {
      setOnChainNodes((prev) => prev + (Math.random() > 0.7 ? 1 : 0));
      setMicroSolTps(() => Math.floor(400 + Math.random() * 120));
      setTotalSolBurnt((prev) =>
        parseFloat((prev + Math.random() * 0.05).toFixed(2)),
      );
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const copyToClipboard = async (text: string, index: number) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIndex(index);
      setTimeout(() => {
        setCopiedIndex(null);
      }, 1500);
    } catch {
      // Clipboard permissions denied or unavailable — fail silently.
    }
  };

  const whitepaperSections: Record<
    TabId,
    { index: string; title: string; content: string; bullets: string[] }
  > = {
    abstract: {
      index: "01",
      title: "Overview: Multi-Route Compute Multiplexing",
      content:
        "Today's decentralized compute networks tend to choke under transaction load and suffer from unpredictable latency. Ordinary machines can supply raw compute, but they offer no built-in way to prove that work was actually done safely. Our protocol takes a different approach: it routes jobs through hardware-isolated Trusted Execution Environments (TEEs) that settle instantly against a high-throughput Solana ledger. Instead of trusting a single machine, clients get a verified, anonymized pipeline — letting sensitive workloads run across untrusted, distributed peers without giving up compliance guarantees.",
      bullets: [
        "No more manual month-end invoicing — settlement happens automatically, job by job.",
        "Every peer is verified through hardware-backed keys before it ever touches a request.",
        "Routes fail over automatically the moment a pathway underperforms.",
      ],
    },
    tokenomics: {
      index: "02",
      title: "Micro-Incentives & On-Chain Settlement",
      content:
        "Because settlement runs directly on Solana, the protocol adds almost no overhead — payments clear in sub-millisecond channels. Node operators are paid continuously: per token processed, per megabyte cached, per packet routed. Payout size adjusts in real time based on how dense the local network is, how fast the hardware runs, and how reliably a node has stayed online.",
      bullets: [
        "Users pay a flat micro-fee per request — currently $0.0001 per routed job.",
        "Operators receive payouts straight into their own non-custodial wallet, no intermediary.",
        "A share of protocol fees is used to buy back and burn tokens, adding deflationary pressure.",
      ],
    },
    cryptography: {
      index: "03",
      title: "Hardware Attestation & Enclave Security",
      content:
        "Every node proves itself before it can join the network. Each host submits a signed attestation certificate generated by its own secure processor — Intel SGX or AMD SEV-SNP. The network checks that certificate against manufacturer root keys on-chain, confirming the node is running inside an isolated memory enclave that no operator, including the host itself, can peek into.",
      bullets: [
        "Every connection carries a fresh proof-of-isolation check — no exceptions.",
        "Session keys rotate dynamically, keeping tunnels anonymous end to end.",
        "Nodes that fail a check lose their routing privileges automatically, no manual review needed.",
      ],
    },
  };

  const tabOrder: TabId[] = ["abstract", "tokenomics", "cryptography"];

  const setupCommands: { title: string; cmd: string }[] = [
    {
      title: "Install the daemon (Ubuntu / Debian)",
      cmd: "curl -sS https://protocol.dev/install.sh | bash",
    },
    {
      title: "Or run it in a container",
      cmd: 'docker run -d --name protocol-node -e PRIVATE_KEY="YOUR_KEY" aetheris/daemon:latest',
    },
    {
      title: "Register with the regional indexer",
      cmd: 'protocol-admin register --node-name="London-Core-H100"',
    },
  ];

  const telemetry = [
    { label: "SETTLEMENT SPEED", value: `${microSolTps}`, unit: "tps" },
    {
      label: "REGISTERED NODES",
      value: onChainNodes.toLocaleString(),
      unit: "",
    },
    {
      label: "TOTAL BURNED",
      value: totalSolBurnt.toFixed(2),
      unit: "SOL",
    },
  ];

  return (
    <div className="w-full flex flex-col text-left">
      {/* Hero — copy + live node mesh */}
      <section className="pt-16 pb-16 px-6 max-w-7xl mx-auto w-full">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-6">
            <span className="font-label-caps text-brand-green mb-4 tracking-widest block bg-brand-green-bg/20 self-start px-2.5 py-1 rounded-full text-[10px] w-fit">
              DOCS & LIVE NETWORK DATA
            </span>
            <h1 className="font-display-lg text-brand-dark tracking-tighter leading-[1.08] mb-6">
              Everything you need to run a node —{" "}
              <span className="text-brand-green-light block italic font-medium mt-1">
                and watch the network live.
              </span>
            </h1>
            <p className="font-body-lg text-brand-gray max-w-xl mb-2 leading-relaxed">
              Browse the whitepaper for the mechanics behind our attestation
              model, get a node running in a few minutes with Ubuntu or
              Docker, and keep an eye on network throughput in real time.
            </p>
          </div>

          {/* Signature element: live routing mesh */}
          <div className="lg:col-span-6">
            <div className="bg-brand-dark rounded-[28px] border border-zinc-800 p-6 md:p-8 relative overflow-hidden">
              <div className="flex items-center gap-2 mb-4 select-none">
                <span className="relative flex h-2 w-2">
                  <span className="motion-reduce:hidden animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-green-bg opacity-60" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-brand-green-bg" />
                </span>
                <span className="font-label-caps text-[10px] text-zinc-400 tracking-widest uppercase">
                  Active routing paths
                </span>
              </div>

              <svg
                viewBox="0 0 360 240"
                className="w-full h-auto"
                role="img"
                aria-label="Diagram of active node connections routing across the network"
              >
                {meshLinks.map(([fromId, toId]) => {
                  const from = meshNodes.find((n) => n.id === fromId)!;
                  const to = meshNodes.find((n) => n.id === toId)!;
                  return (
                    <line
                      key={`${fromId}-${toId}`}
                      x1={from.x}
                      y1={from.y}
                      x2={to.x}
                      y2={to.y}
                      className="stroke-zinc-700"
                      strokeWidth={1}
                    />
                  );
                })}

                {meshNodes.map((node, i) => (
                  <g key={node.id}>
                    <motion.circle
                      cx={node.x}
                      cy={node.y}
                      r={5}
                      className="fill-brand-green-bg motion-reduce:animate-none"
                      animate={{ opacity: [0.5, 1, 0.5] }}
                      transition={{
                        duration: 2.6,
                        repeat: Infinity,
                        delay: i * 0.3,
                        ease: "easeInOut",
                      }}
                    />
                    {node.label && (
                      <text
                        x={node.x + 10}
                        y={node.y + 4}
                        className="fill-zinc-400 text-[9px]"
                        fontFamily="monospace"
                      >
                        {node.label}
                      </text>
                    )}
                  </g>
                ))}
              </svg>
            </div>
          </div>
        </div>
      </section>

      {/* Live Telemetry — single ledger strip */}
      <section className="py-10 px-6 bg-brand-dark text-white w-full border-y border-zinc-800">
        <div className="max-w-7xl mx-auto w-full">
          <div className="grid grid-cols-1 sm:grid-cols-3 divide-y sm:divide-y-0 sm:divide-x divide-zinc-800">
            {telemetry.map((stat) => (
              <div
                key={stat.label}
                className="py-5 sm:py-0 sm:px-8 first:sm:pl-0 last:sm:pr-0 flex flex-col gap-1.5"
              >
                <span className="font-label-caps text-zinc-500 text-[9px] tracking-widest font-bold uppercase">
                  {stat.label}
                </span>
                <div className="flex items-baseline gap-1.5">
                  <span className="text-3xl font-mono text-white font-bold tracking-tight">
                    {stat.value}
                  </span>
                  {stat.unit && (
                    <span className="text-[11px] text-brand-green-bg font-bold font-mono">
                      {stat.unit}
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Whitepaper reader — spine-tab layout */}
      <section className="py-24 px-6 bg-brand-cream/60 border-b border-brand-light-beige/30 w-full">
        <div className="max-w-7xl mx-auto w-full">
          <div className="max-w-xl text-left mb-12 space-y-3">
            <span className="font-label-caps text-brand-green font-bold tracking-wider text-[11px]">
              RESEARCH
            </span>
            <h2 className="font-display-md text-brand-dark tracking-tight leading-none text-3xl md:text-4xl">
              Whitepaper, in brief
            </h2>
            <p className="font-body-sm text-brand-gray leading-relaxed text-[13.5px]">
              A quick look at "Protocol v4: Hardware-Isolated Multipath
              Compute Networks." Pick a section to preview it, or jump to the
              full paper.
            </p>
          </div>

          <div className="flex flex-col lg:flex-row items-stretch">
            {/* Index tabs — visually bound to the paper card on desktop */}
            <div className="flex lg:flex-col gap-2 lg:gap-0 overflow-x-auto lg:overflow-visible select-none pb-2 lg:pb-0">
              {tabOrder.map((id) => {
                const section = whitepaperSections[id];
                const isActive = activeResTab === id;
                return (
                  <button
                    key={id}
                    type="button"
                    onClick={() => setActiveResTab(id)}
                    className={`shrink-0 lg:shrink text-left px-5 py-4 rounded-xl lg:rounded-l-2xl lg:rounded-r-none border transition-all cursor-pointer lg:-mr-px lg:z-10 min-w-[180px] lg:min-w-[220px] ${
                      isActive
                        ? "bg-white border-brand-green text-brand-green lg:border-r-white"
                        : "border-brand-light-beige hover:border-brand-gray bg-white/40 text-brand-dark"
                    }`}
                  >
                    <span
                      className={`font-mono text-[10px] tracking-widest block mb-1 ${
                        isActive ? "text-brand-green" : "text-brand-gray"
                      }`}
                    >
                      {section.index}
                    </span>
                    <h4 className="font-body-sm font-semibold text-[13.5px] leading-tight">
                      {section.title.split(":")[0]}
                    </h4>
                  </button>
                );
              })}
            </div>

            {/* Paper card */}
            <div className="flex-1 bg-white border border-brand-light-beige rounded-[32px] lg:rounded-l-none p-8 md:p-10 shadow-sm text-left relative">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeResTab}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -12 }}
                  transition={{ duration: 0.25 }}
                  className="space-y-6"
                >
                  <p className="font-label-caps text-brand-green tracking-wide text-[10.5px] font-bold">
                    EXCERPT · SEC. V4-{whitepaperSections[activeResTab].index}
                  </p>
                  <h3 className="font-display font-medium text-[24px] text-brand-dark leading-tight border-b border-brand-cream pb-4">
                    {whitepaperSections[activeResTab].title}
                  </h3>

                  <p className="font-display font-normal text-[17px] text-zinc-700 leading-relaxed italic first-letter:text-4xl first-letter:font-bold first-letter:font-display first-letter:float-left first-letter:mr-2">
                    {whitepaperSections[activeResTab].content}
                  </p>

                  <div className="space-y-3 pt-4">
                    <h5 className="font-sans text-[11px] text-brand-dark font-bold tracking-wider uppercase select-none">
                      Key Points:
                    </h5>
                    <ul className="space-y-2.5 text-xs text-brand-gray font-sans list-none">
                      {whitepaperSections[activeResTab].bullets.map((bullet) => (
                        <li key={bullet} className="flex gap-2.5 items-start">
                          <Check
                            size={14}
                            className="text-brand-green shrink-0 mt-0.5"
                          />
                          <span>{bullet}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="flex items-center justify-between mt-8 pt-6 border-t border-brand-cream">
                    <button
                      type="button"
                      onClick={() => onStartEarning?.()}
                      className="inline-flex items-center gap-1.5 font-label-caps text-[10.5px] tracking-wider text-white bg-brand-green font-bold px-4 py-2.5 rounded-full hover:opacity-90 transition-opacity cursor-pointer"
                    >
                      <span>START RUNNING A NODE</span>
                      <ChevronRight size={12} />
                    </button>

                    <button
                      type="button"
                      onClick={() => onNavigateToDocs?.()}
                      className="inline-flex items-center gap-1.5 font-label-caps text-[10.5px] tracking-wider text-brand-green font-bold hover:text-brand-green-light hover:underline cursor-pointer"
                    >
                      <span>READ THE FULL PDF</span>
                      <ExternalLink size={12} />
                    </button>
                  </div>
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
        </div>
      </section>

      {/* Setup guide — numbered sequence */}
      <section className="py-24 px-6 max-w-7xl mx-auto w-full">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 items-start">
          <div className="lg:col-span-4 space-y-6 order-1">
            <span className="font-label-caps text-brand-green font-bold tracking-wider text-[11px] block text-left">
              SETUP
            </span>
            <h2 className="font-display-md text-brand-dark tracking-tight leading-none text-3xl md:text-4xl">
              Get a node running
            </h2>
            <p className="font-body-md text-brand-gray leading-relaxed text-[14px]">
              Three steps, in order. Copy each command as you reach it — most
              operators are live and earning in under three minutes.
            </p>

            <div className="p-4.5 bg-brand-cream border border-brand-light-beige/35 rounded-xl flex gap-3 text-xs leading-normal text-brand-gray select-none">
              <Info size={16} className="text-brand-green shrink-0 mt-0.5" />
              <p>
                <strong>Before you start:</strong> confirm CPU virtualization
                (Intel VT-x / AMD-V) and secure enclave support (SGX / SEV)
                are enabled in your BIOS.
              </p>
            </div>
          </div>

          <div className="lg:col-span-8 bg-zinc-950 text-white rounded-[24px] p-6 md:p-8 space-y-0 border border-zinc-800 order-2">
            {setupCommands.map((item, idx) => (
              <div
                key={item.title}
                className="flex gap-4 py-6 border-b border-zinc-900 last:border-0 first:pt-0 last:pb-0"
              >
                <span className="font-mono text-[11px] text-zinc-600 shrink-0 pt-0.5">
                  {String(idx + 1).padStart(2, "0")}
                </span>

                <div className="flex-1 space-y-2.5 text-left">
                  <span className="text-[11px] font-sans font-bold text-zinc-400 block tracking-wider uppercase select-none">
                    {item.title}
                  </span>

                  <div className="bg-black text-emerald-400 font-mono text-xs rounded-xl p-4 flex justify-between items-center gap-4 relative group overflow-x-auto select-all">
                    <code>{item.cmd}</code>

                    <button
                      type="button"
                      onClick={() => copyToClipboard(item.cmd, idx)}
                      className="p-1 px-2.5 bg-zinc-900 border border-zinc-800 text-zinc-400 rounded-lg text-[10px] hover:text-white hover:border-zinc-700 transition-all font-sans flex items-center gap-1.5 shrink-0 cursor-pointer"
                    >
                      {copiedIndex === idx ? (
                        <>
                          <Check size={11} className="text-emerald-500" />
                          <span className="text-emerald-500 font-bold">
                            COPIED
                          </span>
                        </>
                      ) : (
                        <>
                          <Copy size={11} />
                          <span>COPY CMD</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}